thiscoding/.eslintrc.json, thiscoding/.prettierrc.json, thiscoding/package-lock.json, thiscoding/package.json
[ARVU-63]
[ARVU-63]: https://gadigoodi.atlassian.net/browse/ARVU-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ARVU-63 chore: eslint, prettier 설정

thiscoding/.husky/pre-commit, thiscoding/.husky/pre-push, thiscoding/package-lock.json, thiscoding/package.json
[ARVU-64]
[ARVU-64]: https://gadigoodi.atlassian.net/browse/ARVU-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ARVU-64 chore: husky 설치 및 설정

thiscoding/.husky/pre-commit, thiscoding/.husky/pre-push, thiscoding/package.json
[ARVU-65]
[ARVU-65]: https://gadigoodi.atlassian.net/browse/ARVU-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ARVU-65 chore: lint-staged 설정 추가

thiscoding/package-lock.json, thiscoding/package.json
mui icons, autoprefixer json 추가
=> ARVU-66 build: mui, autoprefixer install

package-lock.json, thiscoding/app/(components)/SideTap.tsx, thiscoding/app/globals.css, thiscoding/app/mypage/invitations/page.tsx, thiscoding/package-lock.json, thiscoding/package.json
- 마이페이지, 관리자페이지 사이드탭 퍼블리싱
- mui, react-icons 사용
=> ARVU-68 feat: 마이페이지, 관리자페이지 사이드탭 퍼블리싱

thiscoding/app/(components)/common/Headers.tsx
=> ARVU-31 feat: 상단바 생성

thiscoding/app/(components)/CodingroomsModal.tsx, thiscoding/package-lock.json, thiscoding/package.json
=> ARVU-70 Feat/codingrooms modal

thiscoding/app/(components)/CodingroomsModal.tsx, thiscoding/package-lock.json
=> ARVU-70 feat: 코드방 생성 모달 퍼블리싱 완성

thiscoding/app/(components)/Top10.tsx
메인페이지 실시간 질문 & 답변 TOP10에 들어가는 컴포넌트 생성
=> ARVU-28 feat: Top10 컴포넌트 생성

thiscoding/app/(components)/common/LogIn.tsx, thiscoding/app/(components)/common/SignUp.tsx
=> ARVU-28 feat: 로그인, 회원가입 모달 생성

thiscoding/package-lock.json, thiscoding/package.json
=> ARVU-21 build: 슬라이드 라이브러리 모듈 설치

thiscoding/app/(components)/common/Headers.tsx
=> ARVU-28 chore: 헤더에 주소 수정

thiscoding/app/(components)/codingrooms/CodingroomsModal.tsx, thiscoding/app/(components)/common/Headers.tsx
=> ARVU-21 chore: 헤더에서 코딩방 생성 모달

thiscoding/app/(components)/Top10.tsx, thiscoding/app/globals.css
=> ARVU-21 chore: ellipsis 적용

thiscoding/app/(components)/codingrooms/CodeEditor.tsx
=> ARVU-89 feat: 코드방 채팅탭, AI 채팅탭 퍼블리싱

thiscoding/app/(components)/codingrooms/CodeEditor.tsx, thiscoding/app/(components)/codingrooms/CodingroomsModal.tsx
코드방 생성 모달의 기존 드롭다운 요소를 select 태그로 변경
=> ARVU-70 fix: 코드방 생성 모달 수정

thiscoding/app/(components)/codingrooms/CodeEditor.tsx, thiscoding/app/(components)/codingrooms/CodingroomsModal.tsx
Piston API를 사용하여 에디터가 지원하는 언어들에 대한 컴파일 기능을 구현했습니다.
지원 언어에서 HTML, CSS, PHP, SQL, R 제외하고 C를 추가했습니다.
실행 후 컴파일이 끝나는 시점까지, 실행 버튼 클릭과 에디터 타이핑을 비활성화되도록 하였습니다.
=> ARVU-50 feat: 코드방 에디터 컴파일 기능 구현

thiscoding/app/(apis)/webSocket.ts, thiscoding/package-lock.json, thiscoding/package.json
소켓 통신에 필요한 SockJS 및 StompJS 추가
=> ARVU-50 build: sockJS, stompJS 추가

thiscoding/app/(models)/admin/adminNotices/AdminNoticesDetailDTO.ts, thiscoding/app/(models)/admin/adminNotices/AdminNoticesListDTO.ts, thiscoding/app/(models)/users/User.ts
=> ARVU-24 chore:관리자 공지사항 타입 작성

thiscoding/app/(apis)/admin/adminApi.ts, thiscoding/app/(components)/admin/adminNotices/AdminNotices.tsx, thiscoding/app/(components)/admin/adminNotices/AdminNoticesContent.tsx, thiscoding/app/(components)/notices/[notices_Id]/NoticesDetail.tsx, thiscoding/app/(hooks)/admin/useAdmin.ts
유지보수에 용이하게 api와 hook은 별도의 패키지로 분리해서 사용하도록 함.
=> ARVU-24 feat:관리자 공지사항 작성,삭제,수정,조회 구현 및 api,hook 폴더로 분리

thiscoding/app/(components)/admin/adminNotices/postNotices/AdminPostNotices.tsx, thiscoding/app/(components)/admin/notices/[adminNotice_Id]/AdminNoticesDetail.tsx
api,hook으로 분리한 코드를 컴포넌트에서 적용하여 기능 구현.
=> ARVU-24 feat:관리자 CURD 기능 컴포넌트에 적용

thiscoding/app/(apis)/qna/qnaApi.ts, thiscoding/app/(components)/qna/post-qna/ToastUi.tsx, thiscoding/app/(components)/qna/post-qna/UserPostQnA.tsx, thiscoding/app/(hooks)/qna/useQnA.ts, thiscoding/package-lock.json, thiscoding/package.json
토스트 ui를 통해서 qna 작성 기능구현.
base64 > url로 변환해주는 백엔드 통신 코드 작성
=> ARVU-25 feat:토스트ui를 사용한 QnA 작성 기능 구현

thiscoding/app/(apis)/qna/qnaApi.ts, thiscoding/app/(components)/qna/[qna_Id]/QnADetail.tsx, thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Comment.tsx, thiscoding/app/(hooks)/qna/useQnA.ts, thiscoding/app/(models)/qna/QnaCommentType.ts
댓글조회 기능구현 및 Type 파일 추가.
nickname은 나중에 수정해야함.
=> ARVU-26 feat:QnA 댓글조회 기능구현 및 type 추가

thiscoding/app/(apis)/userApi.ts, thiscoding/app/(components)/common/LogIn.tsx, thiscoding/app/page.tsx
=> ARVU-34 chore: 메인 페이지 로그인 모달

thiscoding/app/(components)/common/Headers.tsx, thiscoding/app/(components)/common/SignUp.tsx, thiscoding/app/(hooks)/useSignUp.ts, thiscoding/app/store/store.tsx
=> ARVU-34 chore: 회원가입 모달

thiscoding/app/globals.css, thiscoding/app/mypage/page.tsx
=> ARVU-37 chore: 마이페이지 기능 구현

thiscoding/app/(components)/common/EmailVerification.tsx, thiscoding/app/(components)/common/FindPassword.tsx
=> ARVU-36 chore: 비밀번호 찾기 모달

thiscoding/app/(components)/Top10.tsx
=> ARVU-21 chore: 메인페이지 top10 수정

thiscoding/app/(components)/common/LogIn.tsx
=> chore:소셜로그인 부분 import 삭제

thiscoding/app/(hooks)/axiosConfig.ts, thiscoding/app/(hooks)/useSignUp.ts
=> fix:이메일 인증코드 body에서 param으로 변경.

thiscoding/app/(apis)/admin/adminApi.ts, thiscoding/app/(apis)/mypage/postQna/postQnaApi.ts, thiscoding/app/(apis)/qna/qnaApi.ts, thiscoding/app/(components)/mypage/qna/PostQnA.tsx
BaseUrl 설정으로 인해 axios 요청시 http://localhost 주소 제거
=> chore:axios를 axiosInstance 객체로 변경

thiscoding/app/(components)/common/Headers.tsx
헤더에서 코드방 생성을 누르면 모달이 켜지지 않는 문제 수정,
user에 name 타입 선언
=> ARVU-31 chore: 헤더 부분에 코드방 안열리는 문제 수정

thiscoding/app/(apis)/qna/qnaApi.ts, thiscoding/app/(components)/admin/adminNotices/postNotices/AdminPostNotices.tsx, thiscoding/app/(components)/qna/post-qna/ToastUi.tsx, thiscoding/app/(components)/qna/post-qna/UserPostQnA.tsx, thiscoding/app/(hooks)/admin/useAdmin.ts, thiscoding/app/(hooks)/qna/useQnA.ts
각각 관리하던 useState를 객체로 통일시키고 handler 대신 onChange에서 spread 연산자를 통해 객체에 저장하도록 변경함.
=> refactor:공지사항,Qna useState,handler 리팩토링

thiscoding/app/(hooks)/axiosConfig.ts
기존 http 요청시 axios에서 axiosInstance객체로 변경하면서, 현재 쿠키 미구현으로 withCredentials 설정 true > false로 변경함.
=> fix:axios 인스턴스 withCredentials 설정 false로 변경

thiscoding/app/(components)/common/LogIn.tsx
로그인 할때 ente 누르면 로그인 가능하게 이벤트 추가
=> ARVU-35 chore: 로그인할때 Enter 이벤트 추가

thiscoding/app/(components)/common/Headers.tsx
=> ARVU-35 chore: 헤더에서 로그아웃

thiscoding/app/(apis)/codingrooms/codingroomsApi.ts, thiscoding/app/(components)/codingrooms/[codingrooms_uuid]/CodeEditor.tsx, thiscoding/app/(hooks)/codingrooms/useCodingrooms.ts, thiscoding/package-lock.json
=> ARVU-50 feat: 파일명 변경 메서드 추가

thiscoding/app/(components)/common/SignUp.tsx, thiscoding/app/(hooks)/useSignUp.ts, thiscoding/app/(hooks)/user/handleLogin.ts, thiscoding/app/(models)/axiosWithAuth.ts
=> ARVU-34 feat: 회원가입 기능

thiscoding/app/(apis)/admin/adminApi.ts, thiscoding/app/(apis)/mypage/postQna/postQnaApi.ts, thiscoding/app/(apis)/qna/qnaApi.ts, thiscoding/app/(components)/admin/adminNotices/AdminNotices.tsx, thiscoding/app/(components)/admin/adminNotices/AdminNoticesContent.tsx, thiscoding/app/(components)/mypage/qna/PostQnA.tsx, thiscoding/app/(components)/qna/QnA.tsx, thiscoding/app/(components)/qna/QnAContent.tsx, thiscoding/app/(components)/qna/[qna_Id]/QnADetail.tsx, thiscoding/app/(components)/qna/[qna_Id]/QnADetailAnswer.tsx, thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Comment.tsx, thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Reply.tsx, thiscoding/app/(components)/qna/post-qna/ToastUi.tsx, thiscoding/app/(components)/qna/post-qna/UserPostQnA.tsx, thiscoding/app/(components)/qna/viewer.css, thiscoding/app/(hooks)/mypage/post-qna/usePostQna.ts, thiscoding/app/(hooks)/qna/useQnA.ts, thiscoding/app/(models)/qna/QnaCommentType.ts, thiscoding/app/(models)/qna/QnaListType.ts
Viewer로 마크다운 언어 마크업으로 변환 출력
Qna 리스트에선 Img태그 안보이도록 수정
Qna 댓글 useQuery과 useMutation으로 데이터 및 상태관리
=> feat:ToastUi Viewer 사용 및 Comment useMutation으로 관리

thiscoding/app/(components)/common/Headers.tsx, thiscoding/app/(models)/axiosWithAuth.ts
- axiosNonAuth에서 토큰 삭제
- 로그인 및 회원가입 필요 시 모달 띄우는 기능 구현
=> ARVU-12 chore: axios에서 토큰 삭제하고, 로그인/ 회원가입 모달 표시

thiscoding/app/(apis)/userApi.ts, thiscoding/app/(hooks)/useSignUp.ts, thiscoding/app/(hooks)/user/useLogin.ts, thiscoding/app/store/store.tsx
- 로그인, 회원가입 기능을 위한 훅 구현
- 로그인, 회원가입 모달 표시 로직 추가
- Zustand store로 로그인 상태 관리 추가
=> ARVU-12 refactor: 로그인/회원가입 모달과 훅, store 수정

thiscoding/app/page.tsx
=> ARVU-12 chore: 메인 페이지 로그인 테스트

thiscoding/app/mypage/page.tsx
=> ARVU-37 chore: 마이페이지 store 수정

thiscoding/app/(hooks)/user/useLogin.ts
=> ARVU-35 fix: 로그인 실패시 알림 메시지 추가

thiscoding/src/shared/layouts/header/Logo.tsx, thiscoding/src/shared/layouts/header/NavMenu.tsx, thiscoding/src/shared/layouts/header/UserMenu.tsx, thiscoding/src/shared/layouts/header/index.tsx
=> ARVU-12 refactor: 헤더 컴포넌트 분리 및 리팩토링

thiscoding/src/shared/store/store.tsx
회원의 role을 확인하여 admin일 경우 헤더 마이페이지 → 관리자 페이지
=> ARVU-38 feat: 회원 역할 확인 기능 추가 (admin 여부 판별)

thiscoding/src/features/auth/apis/axiosWithAuth.ts, thiscoding/src/features/auth/apis/userApi.ts, thiscoding/src/features/auth/log-in/useLogin.ts, thiscoding/src/features/auth/sign-up/useSignUp.ts, thiscoding/src/shared/ui/modals/LogIn.tsx
로그인시 로그인 상태 저장을 체크하면 로그인 상태를 저장함
=> ARVU-35 feat: 로그인 상태 저장 기능 추가
